/**
 * scripts/i18n-todo.mjs
 *
 * Lists every message key that is still falling back to English.
 *
 *   npm run i18n:todo            writes docs/i18n-todo.md, exits 0
 *   npm run i18n:todo -- --check exits 1 if anything is untranslated
 *
 * The `--check` mode is for the day FR is meant to be complete. Until then the
 * count is the backlog, and the point of the file is that the backlog is a number
 * somebody can look at rather than a feeling.
 *
 * Parsed rather than imported, so this stays dependency free and runs without a
 * build step. Both dictionaries are flat objects of single-quoted string
 * literals, which is one of the reasons the keys are flat.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';

const CHECK = process.argv.includes('--check');

/** Pulls `'key': 'value',` pairs out of a dictionary module. */
const parse = (source) => {
  const entries = new Map();
  const pattern = /^\s*'([^']+)':\s*'((?:[^'\\]|\\.)*)'/gm;
  let match;
  while ((match = pattern.exec(source)) !== null) {
    entries.set(match[1], match[2]);
  }
  return entries;
};

const en = parse(await readFile('src/i18n/en.ts', 'utf8'));
const fr = parse(await readFile('src/i18n/fr.ts', 'utf8'));

const missingKey = [];
const emptyValue = [];

for (const [key, english] of en) {
  if (!fr.has(key)) missingKey.push([key, english]);
  else if (fr.get(key).trim() === '') emptyValue.push([key, english]);
}

/** A key FR carries that EN does not is a rename nobody finished. */
const orphaned = [...fr.keys()].filter((key) => !en.has(key));

const outstanding = missingKey.length + emptyValue.length;
const done = en.size - outstanding;

const group = (rows) => {
  const byNamespace = new Map();
  for (const [key, english] of rows) {
    const namespace = key.split('.')[0];
    if (!byNamespace.has(namespace)) byNamespace.set(namespace, []);
    byNamespace.get(namespace).push([key, english]);
  }
  return [...byNamespace.entries()].sort(([a], [b]) => a.localeCompare(b));
};

const lines = [
  '# French translation manifest',
  '',
  'Generated by `npm run i18n:todo`. Do not edit by hand.',
  '',
  `**${outstanding} of ${en.size} keys outstanding.** ${done} translated.`,
  '',
  'Target locale is French for Quebec. An outstanding key is not broken: it falls',
  'back to English at the call site, so `?lang=fr` renders a complete screen today.',
  'It is listed here so the backlog is a number rather than a feeling.',
  '',
];

if (orphaned.length > 0) {
  lines.push(
    '## Orphaned',
    '',
    'Present in `fr.ts` and absent from `en.ts`. A rename that stopped halfway.',
    '',
    ...orphaned.map((key) => `- \`${key}\``),
    '',
  );
}

if (outstanding === 0) {
  lines.push('Nothing outstanding.', '');
} else {
  lines.push('## Outstanding, by screen', '');
  for (const [namespace, rows] of group([...missingKey, ...emptyValue])) {
    lines.push(`### \`${namespace}\``, '', '| Key | English |', '|---|---|');
    for (const [key, english] of rows) {
      lines.push(`| \`${key}\` | ${english.replace(/\|/g, '\\|')} |`);
    }
    lines.push('');
  }
}

await mkdir('docs', { recursive: true });
await writeFile('docs/i18n-todo.md', lines.join('\n'));

console.log(
  `${outstanding} of ${en.size} keys outstanding` +
    (orphaned.length ? `, ${orphaned.length} orphaned` : '') +
    '. Written to docs/i18n-todo.md',
);

if (CHECK && (outstanding > 0 || orphaned.length > 0)) process.exit(1);
